version: "3"

volumes:
  mysql-data:
  orsee-data:

services:
  database:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    image: thelfensdrfer/orsee:latest
    build:
      context: ./orsee
    depends_on:
      - database
    volumes:
      - orsee-data:/orsee
      - ./orsee/settings.php:/orsee/config/settings.php:ro
  cron:
    build:
      context: ./cron
    depends_on:
      - database
    volumes:
      - orsee-data:/orsee
      - ./orsee/settings.php:/orsee/config/settings.php:ro
  nginx:
    image: nginx:stable
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/orsee.conf:/etc/nginx/conf.d/default.conf:ro
      - orsee-data:/orsee
