version: "3"

volumes:
  mysql-data:

services:
  database:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build:
      context: ./orsee
    depends_on:
      - database
    volumes:
      - ./orsee/settings.php:/orsee/config/settings.php:ro
  nginx:
    image: nginx
    ports:
      - 80:8080
    depends_on:
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d/
